# Generated by Django 6.0.4 on 2026-07-24 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('form_builder', '0002_enquiryform_email_notifications'),
    ]

    operations = [
        migrations.AddField(
            model_name='enquiryform',
            name='footer_text',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='enquiryform',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='form_builder/logos/'),
        ),
        migrations.AddField(
            model_name='enquiryform',
            name='redirect_delay_seconds',
            field=models.PositiveSmallIntegerField(default=5),
        ),
    ]
